/*
SQLyog Ultimate - MySQL GUI v8.21 
MySQL - 5.5.5-10.1.9-MariaDB : Database - wwwinfom_sourcedb
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`wwwinfom_sourcedb` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */;

USE `wwwinfom_sourcedb`;

/*Table structure for table `home_posts` */

DROP TABLE IF EXISTS `home_posts`;

CREATE TABLE `home_posts` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `home_category_id` int(5) NOT NULL,
  `pointid` int(11) NOT NULL,
  `pointname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pointcreated` datetime DEFAULT NULL,
  `point_seoname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `classid` int(11) DEFAULT NULL,
  `class_bntitle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `class_title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `class_metatag` text COLLATE utf8_unicode_ci,
  `class_bn_details` text COLLATE utf8_unicode_ci,
  `class_details` text COLLATE utf8_unicode_ci,
  `class_image` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `placetype_icon` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `placetype_pluralname` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `placetype_seoname` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `publishdate` datetime DEFAULT NULL,
  `unpublishdate` datetime DEFAULT NULL,
  `language` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `isactive` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*Data for the table `home_posts` */

insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (44,1,1159380,'Dhaka Medical College and Hospital','2016-08-09 15:26:49','dhaka-medical-college-and-hospital',154,'ঢাকা মেডিকেল কলেজ হাসপাতাল','Dhaka Medical College and Hospital','Dhaka Medical College and Hospital listed in Hospital & Clinic category. Location of Dhaka Medical College and Hospital is Secretariate Rd. Contact informations of Dhaka Medical College and Hospital is,  Address: Secretariate Rd, Dhaka 1000, Bangladesh','','','hospitals/photogallery/small/InfoMap24_place_dhaka-medical-college-and-hospital_9_18_10_30_03_10_33_dmch@hospi.dghs.gov.bd.jpg','fa fa-hospital-o','hospitals','health-and-medicine',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (45,1,1159244,'Al-Helal Specialized Hospital Ltd.',NULL,'al-helal-specialized-hospital-ltd-',30,'আল-হেলাল বিশেষায়িত হাসপাতাল লিমিটেড','Al-Helal Specialized Hospital Ltd.','Al-Helal Specialized Hospital Ltd. listed in  category. Location of Al-Helal Specialized Hospital Ltd. is . Contact informations of Al-Helal Specialized Hospital Ltd. is,  Phone: +880-2-9008181, 9006820,  Address: 150, Rokeya Sarani Probata Mirpur','','','hospitals/photogallery/small/InfoMap24_place_al-helal-specialized-hospital-ltd-_11_18_10_30_04_10_09_index.jpg','fa fa-hospital-o','hospitals','health-and-medicine',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (46,1,1159372,'Sir Salimullah Medical College Mitford Hospital','2016-08-09 14:29:00','sir-salimullah-medical-college-mitford-hospital',147,'স্যার সলিমুল্লাহ মেডিকেল কলেজ মিটফোর্ড হাসপাতাল','Sir Salimullah Medical College Mitford Hospital','Sir Salimullah Medical College Mitford Hospital listed in Hospital & Clinic category. Location of Sir Salimullah Medical College Mitford Hospital is Mitford Rd. Contact informations of Sir Salimullah Medical College Mitford Hospital is, ','','','hospitals/photogallery/small/InfoMap24_place_sir-salimullah-medical-college-mitford-hospital_10_18_10_30_04_10_37_index.jpg','fa fa-hospital-o','hospitals','health-and-medicine',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (47,1,1159248,'Apollo Hospital Dhaka',NULL,'apollo-hospital-dhaka',34,'অ্যাপোলো হাসপাতালে ঢাকা','Apollo Hospital Dhaka','Apollo Hospital Dhaka listed in  category. Location of Apollo Hospital Dhaka is . Contact informations of Apollo Hospital Dhaka is,  Phone: (NULL),  Address: Plot # 81, Block-E, Bashundhara R/A','','','hospitals/photogallery/small/InfoMap24_place_apollo-hospital-dhaka_10_18_10_30_04_10_04_index.jpg','fa fa-hospital-o','hospitals','health-and-medicine',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (48,1,1159384,'BIRDEM','2016-08-09 16:05:43','birdem',158,'বারডেম','BIRDEM','BIRDEM listed in Hospital & Clinic category. Location of BIRDEM is Shahbagh. Contact informations of BIRDEM is, ','','','hospitals/photogallery/small/InfoMap24_place_birdem_7_18_10_30_04_10_08_index.jpg','fa fa-hospital-o','hospitals','health-and-medicine',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (49,1,1159350,'United Hospital Ltd',NULL,'united-hospital-ltd-',136,'ইউনাইটেড হাসপাতাল লিমিটেড','United Hospital Ltd','United Hospital Ltd. listed in  category. Location of United Hospital Ltd. is . Contact informations of United Hospital Ltd. is,  Phone: +880-2-8836000, 8836444,  Address: Plot # 15, Road # 71, Gulshan','','','hospitals/photogallery/small/InfoMap24_place_united-hospital-ltd-_13_18_10_13_05_10_09_United-Hospital-2.jpg','fa fa-hospital-o','hospitals','health-and-medicine',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (50,2,41,'Currency Museum','2015-04-25 06:11:28','currency-museum',42,'টাকা জাদুঘর','Currency Museum','Currency Museum listed in Notable Places category. Contact information of Currency Museum is Address: Mirpur  Road, Dhaka, Bangladesh','','','places/photogallery/small/InfoMap24_places_145_18_10_31_04_10_15_images.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (51,2,1071,'Lalbagh Fort','2015-05-29 12:59:33','lalbagh-fort',1075,'লালবাগ কেল্লা','Lalbagh Fort','Lalbagh Fort listed in Notable Places category. Location of Lalbagh Fort is Lalbagh. Contact informations of Lalbagh Fort is,  Address: Lalbagh, Dhaka, Bangladesh\r\n\r\n','','','places/photogallery/small/InfoMap24_places_51_18_10_31_04_10_01_index.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (52,2,248,'Bangladesh National Museum','2015-04-26 15:01:30','bangladesh-national-museum',250,'বাংলাদেশ জাতীয় জাদুঘর','Bangladesh National Museum','Bangladesh National Museum listed in Notable Places category. Contact information of Bangladesh National Museum is Address: Shahbagh  Road, Dhaka, Bangladesh bangladeshmuseum.gov.bd 02-8619396','','','places/photogallery/small/InfoMap24_places_162_18_10_31_04_10_02_index.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (53,2,216,'Botanical Garden','2015-04-25 08:30:01','botanical-garden',217,'বোটানিক্যাল গার্ডেন','Botanical Garden','Botanical Garden listed in Notable Places category. Contact information of Botanical Garden is Address: ','','','places/photogallery/small/InfoMap24_places_148_18_10_31_05_10_04_images.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (54,3,1159369,'Bichanakandi Water on the Rocks','2016-08-06 18:00:10','bichanakandi-water-on-the-rocks',1424,'বিছানাকান্দি','Bichanakandi Water on the Rocks','BICHANAKANDI Water on the Rocks listed in Notable Places category. Location of BICHANAKANDI Water on the Rocks is BICHANAKANDI. Contact informations of BICHANAKANDI Water on the Rocks is,  Address: Bisnakandi, Sylhet, Bangladesh','','','places/photogallery/small/InfoMap24_places_149_18_10_31_05_10_28_imagesd.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (55,3,1159363,'Ratargul Swamp Forest','2016-08-06 15:27:35','ratargul-swamp-forest',1418,'রাতারগুল সোয়াম্প ফরেস্ট','Ratargul Swamp Forest','Ratargul Swamp Forest listed in Notable Places category. Location of Ratargul Swamp Forest is Ratargul Swamp Forest. Contact informations of Ratargul Swamp Forest is,  Address:  Gowainghat, Sylhet, Bangladesh','','','places/photogallery/small/InfoMap24_places_8_18_10_31_05_10_14_imagesd.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (56,3,578,'Laboni Beach','2015-05-02 06:30:32','laboni-beach',580,'লাবনী বিচ','Laboni Beach','Laboni Beach listed in Notable Places category. Contact information of Laboni Beach is Address: ','','','places/photogallery/small/InfoMap24_places_136_18_10_31_05_10_24_images.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (57,3,1159367,'Bhawal National Park','2016-08-06 17:29:03','bhawal-national-park',1422,'ভাওয়াল জাতীয় উদ্যান','Bhawal National Park','Bhawal National Park listed in Notable Places category. Location of Bhawal National Park is Bhawal National Park. Contact informations of Bhawal National Park is,  Address: Gazipur, Dhaka Division of Bangladesh','','','places/photogallery/small/InfoMap24_places_54_18_10_31_05_10_37_indehhx.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (58,3,1159366,'Lawachara National Park','2016-08-06 17:18:11','lawachara-national-park',1421,'লাউয়াছড়া ন্যাশনাল পার্ক','Lawachara National Park','Lawachara National Park listed in Notable Places category. Location of Lawachara National Park is Lawachara. Contact informations of Lawachara National Park is,  Address: Kamalganj Upazila, Maulvi Bazar District ','','','places/photogallery/small/InfoMap24_places_60_18_10_31_05_10_26_Lawa-Chara-National-Park-Bangladesh.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (59,3,1159368,'Madhabkunda waterfall','2016-08-06 17:49:32','madhabkunda-waterfall',1423,'মাধবকুন্ড জলপ্রপাত','Madhabkunda waterfall','Madhabkunda waterfall listed in Notable Places category. Location of Madhabkunda waterfall is Madhabkunda. Contact informations of Madhabkunda waterfall is,  Address: Barlekha Upazila in Moulvibazar District, Sylhet Division','','','places/photogallery/small/InfoMap24_places_46_18_10_31_05_10_57_index.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (60,2,1159361,'Ahsan Manzil','2016-01-27 10:05:07','ahsan-manzil',1416,'আহসান মঞ্জিল','Ahsan Manzil','Ahsan Manzil listed in Notable Places category. Location of Ahsan Manzil is . Contact informations of Ahsan Manzil is,  Address: Sadarghat - Gabtoli Rd\r\nDhaka\r\nBangladesh\r\n','','','places/photogallery/small/InfoMap24_places_163_18_10_31_06_10_56_23826346_1878962425464679_1116106106115749785_o.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);
insert  into `home_posts`(`id`,`home_category_id`,`pointid`,`pointname`,`pointcreated`,`point_seoname`,`classid`,`class_bntitle`,`class_title`,`class_metatag`,`class_bn_details`,`class_details`,`class_image`,`placetype_icon`,`placetype_pluralname`,`placetype_seoname`,`publishdate`,`unpublishdate`,`language`,`isactive`) values (61,2,1159362,'Shahid Zia Shishu Park','2016-01-27 18:19:16','shahid-zia-shishu-park',1417,'শহীদ জিয়া শিশুপার্ক','Shahid Zia Shishu Park','Shahid Zia Shishu Park listed in Notable Places category. Location of Shahid Zia Shishu Park is Ramna. Contact informations of Shahid Zia Shishu Park is,  Phone: 02-8623304,  Address: Shahbag\r\nDhaka\r\nBangladesh\r\n','','','places/photogallery/small/InfoMap24_places_165_18_10_31_06_10_38_index.jpg','fa fa-diamond','places','notable-places',NULL,NULL,NULL,1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
